# Run with:
# ansible-playbook SambaDirectories.yml

---
- name: Configure Samba Directories
  hosts: all
  tasks:

  - name: Put in ORIANS workgroup
    replace:
      path: /etc/samba/smb.conf
      regexp: 'workgroup = WORKGROUP'
      replace: 'workgroup = ORIANS'

  - name: Add AllWrite Share
    blockinfile:
      path: /etc/samba/smb.conf
      marker: "# Allwrite {mark} Ansible Managed Block"
      block: |
        [allwrite]
        comment = Writeable area
        path = /mnt/external/allwrite
        guest ok = Yes
        read only = No

  - name: Add Downloads Share
    blockinfile:
      path: /etc/samba/smb.conf
      marker: "# ExtDownloads {mark} Ansible Managed Block"
      block: |
        [extdownloads]
        comment = External hard drive downloads
        path = /mnt/external/download_files
        guest ok = Yes
        read only = No

  - name: Start Samba service
    ansible.builtin.systemd:
      state: restarted
      name: smb
