# Run with:
# ansible-playbook SetupBackups.yml

---
- name: Setup Backups
  hosts: all
  tasks:

  - name: Create directory for backups
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /mnt/backups
      - /mnt/backups/mediawiki
      - /mnt/backups/birthdays
      - /mnt/backups/backdrop
      - /mnt/backups/mailserver
      - /mnt/backups/snappymail

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: RestoreMediaWiki.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that restores the MediaWiki data"
    ansible.builtin.cron:
      name: "Restore MediaWiki data"
      minute: "0"
      hour: "4"
      job: "/mnt/backups/RestoreMediaWiki.sh"

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: RestoreBirthdays.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that restores the Birthdays data"
    ansible.builtin.cron:
      name: "Restore Birthdays data"
      minute: "5"
      hour: "4"
      job: "/mnt/backups/RestoreBirthdays.sh"

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: RestoreBackdrop.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that restores the Backdrop data
    ansible.builtin.cron:
      name: "Restore Backdrop data"
      minute: "10"
      hour: "4"
      job: "/mnt/backups/RestoreBackdrop.sh"

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: RestoreMailServer.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that restores the MailServer data
    ansible.builtin.cron:
      name: "Restore MailServer data"
      minute: "15"
      hour: "4"
      job: "/mnt/backups/RestoreMailServer.sh"

  - name: Copy the copy script file with owner and permissions
    ansible.builtin.copy:
      src: RestoreSnappyMail.sh
      dest: /mnt/backups
      owner: ajorians
      group: users
      mode: 0777

  - name: Ensure a job that restores the SnappyMail data
    ansible.builtin.cron:
      name: "Restore SnappyMail data"
      minute: "20"
      hour: "4"
      job: "/mnt/backups/RestoreSnappyMail.sh"

  - name: Restart Cron service
    ansible.builtin.systemd:
      state: restarted
      name: cron

