[pbx]
asteriskpi.local

[pbx:vars]
ansible_python_interpreter=/usr/bin/python3
resilio_sync_url=asteriskpisync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
freepbx_url=asteriskpi.orians.org
update_minute=50

[cms]
cms.local

[cms:vars]
use_apache=false
resilio_sync_url=cmdsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=10

[development]
development.local

[development:vars]
resilio_sync_url=developmentsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=20

[backups]
datapi1.local

[backups:vars]
resilio_sync_url=datapi1sync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=30

[download]
download.local

[download:vars]
resilio_sync_url=downloadsync.orians.org
resiliosync_download_path=/mnt/external/sync
update_minute=40

[vpn]
vpn.local

[dns]
#192.168.0.3

[dns:vars]
use_apache=false
resilio_sync_url=dnssync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=50

[photosync]
photosync.local

[photosync:vars]
resilio_sync_url=photosync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=30

[music]
music.local

[music:vars]
resilio_sync_url=musicsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=20

[adc1]
adc1.local

[adc1:vars]
ansible_python_interpreter=/usr/bin/python3
resilio_sync_url=adcsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
freepbx_url=adcpi.orians.org
update_minute=20

[emulator]
emulator.local

[emulator:vars]
resilio_sync_url=emulatorsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=20

#Technially a destop computer
[jellyfin]
jellyfin.local

[jellyfin:vars]
resilio_sync_url=jellyfinsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=35

[taskrunner]
taskrunner.local

[taskrunner:vars]
resilio_sync_url=taskrunnersync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=40

[testpi]
testpi.local

[testpi:vars]
ansible_python_interpreter=/usr/bin/python3
resilio_sync_url=testpisync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=25

[stash]
stash.local

[stash:vars]
ansible_python_interpreter=/usr/bin/python3
resilio_sync_url=stashsync.orians.org
resiliosync_download_path=/opt/DockerSwarmData/resiliosync/downloads
update_minute=25

