# Run with:
# ansible-playbook InstallWget.yml

---
- name: Install Wget
  hosts: all
  tasks:

  - name: Install Wget package on OpenSUSE/SUSE Linux
    zypper:
      name: wget
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

