# Run with:
# ansible-playbook InstallMake.yml

---
- name: Install Make
  hosts: all
  tasks:

  - name: Install Make package on OpenSUSE/SUSE Linux
    zypper:
      name: make
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install MakeInfo package on OpenSUSE/SUSE Linux
    zypper:
      name: makeinfo
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1
