# Run with:
# ansible-playbook InstallJansson.yml

---
- name: Install Jansson
  hosts: all
  tasks:

  - name: Install Jansson library package on OpenSUSE/SUSE Linux
    zypper:
      name: libjansson4
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Jansson library Devel package on OpenSUSE/SUSE Linux
    zypper:
      name: libjansson-devel
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

