# Run with:
# ansible-playbook InstallRar.yml

---
- name: Install Rar
  hosts: all
  tasks:

  - name: Install Rar package on OpenSUSE/SUSE Linux
    zypper:
      name: unrar
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Rar package on Raspberian Linux
    apt:
      name: unrar
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

