# Run with:
# ansible-playbook InstallNDLessSDK.yml

---
- name: Install NDLess SDK
  hosts: development
  tasks:

  - name: Check if NDLess source exists
    stat:
      path: /home/ajorians/Documents/git/Ndless
    register: ndless_exists

  - name: Clone NDLess Source
    become: yes
    become_user: ajorians
    ansible.builtin.git:
      repo: https://github.com/ndless-nspire/Ndless.git
      dest: /home/ajorians/Documents/git/Ndless
    when: ndless_exists.stat.exists == false

  - name: Check if nspire-gcc exists
    stat:
      path: /home/ajorians/Documents/git/Ndless/ndless-sdk/bin/nspire-gcc
    register: nspiregcc_exists

  - name: Run setup script
    become: yes
    become_user: ajorians
    shell:
      cmd: ./build_toolchain.sh
      chdir: /home/ajorians/Documents/git/Ndless/ndless-sdk/toolchain/
    when: nspiregcc_exists.stat.exists == false

  - name: Add NDLess to PATH
    become: yes
    become_user: ajorians
    ansible.builtin.lineinfile:
      path: /home/ajorians/.profile
      line: export PATH=/home/ajorians/Documents/git/Ndless/ndless-sdk/toolchain/install/bin:/home/ajorians/Documents/git/Ndless/ndless-sdk/bin:$PATH


