# Run with:
# ansible-playbook InstallRust.yml

---
- name: Install Rust
  hosts: development
  become: true
  become_user: ajorians
  tasks:

  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust

  - name: Install cargo-make Rust package
    community.general.cargo:
      name: cargo-make

  - name: Install cargo-generate Rust package
    community.general.cargo:
      name: cargo-generate
