# Run with:
# ansible-playbook InstallScreen.yml

---
- name: Install Screen
  hosts: all
  tasks:

  - name: Install Screen package on OpenSUSE/SUSE Linux
    zypper:
      name: screen
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Screen package on Raspberian Linux
    apt:
      name: screen
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

