# Run with:
# ansible-playbook InstallAnsible.yml

---
- name: Install Ansible
  hosts: all
  tasks:

  - name: Install Ansible package on OpenSUSE/SUSE Linux
    zypper:
      name: ansible
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Ansible package on Raspberian Linux
    apt:
      name: ansible
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1
