# Run with:
# ansible-playbook InstallSubversion.yml

---
- name: Install Subversion
  hosts: all
  tasks:

  - name: Install just Subversion package on OpenSUSE/SUSE Linux
    zypper:
      name: subversion
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Subversion package on Raspberian Linux
    apt:
      name: subversion
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

