# Run with:
# ansible-playbook InstallRSync.yml

---
- name: Install RSync
  hosts: all
  tasks:

  - name: Install RSync package on OpenSUSE/SUSE Linux
    zypper:
      name: rsync
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install RSync package on Raspberian Linux
    apt:
      name: rsync
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

