# Run with:
# ansible-playbook InstallPLocate.yml

---
- name: Install PLocate
  hosts: all
  tasks:

  - name: Install PLocate package on OpenSUSE/SUSE Linux
    zypper:
      name: plocate
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install PLocate package on Raspberian Linux
    apt:
      name: plocate
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

