# Run with:
# ansible-playbook InstallPython.yml

---
- name: Install Python
  hosts: all
  tasks:

  - name: Install Python package on OpenSUSE/SUSE Linux
    zypper:
      name: python
      state: present

  - name: Install Python Cryptography package on OpenSUSE/SUSE Linux
    zypper:
      name: python311-cryptography
      state: present

  - name: Install Python3 Devel package on OpenSUSE/SUSE Linux
    zypper:
      name: python311-devel
      state: present

  # Was needed for setting mysql root password
  - name: Install Python PyMySQL package on OpenSUSE/SUSE Linux
    zypper:
      name: python311-PyMySQL
      state: present
