# Run with:
# ansible-playbook InstallZLib.yml

---
- name: Install ZLib
  hosts: development
  tasks:

  - name: Install ZLib devel package on OpenSUSE/SUSE Linux
    zypper:
      name: zlib-ng-devel #ng is Next Generation
      state: present

