# Run with:
# ansible-playbook InstallCron.yml

---
- name: Install Cron
  hosts: all
  tasks:

  - name: Install Cron package on OpenSUSE/SUSE Linux
    zypper:
      name: cron
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Install Cron package on Raspberian Linux
    apt:
      name: cron
      state: present
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1
