# Run with:
# ansible-playbook ZypperUpdate.yml

---
- name: Update Machine
  hosts: all
  tasks:

  - name: Update all packages on OpenSUSE/SUSE Linux
    zypper:
      name: '*'
      state: latest
      allow_vendor_change: true
      force_resolution: true
      replacefiles: true
      update_cache: true
    when:
    - ansible_facts['distribution'].find("openSUSE") != -1

  - name: Update all packages on Raspberian Linux
    apt:
      name: '*'
      state: latest
    when:
    - ansible_facts['distribution'].find("openSUSE") == -1

  - name: Check if a reboot is needed on all SUSE/OpenSUSE based servers
    register: linux_reboot_required_file
    stat:
      path: /boot/do_purge_kernels 
      get_checksum: no

  - name: Reboot the box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: linux_reboot_required_file.stat.exists
