# Run with
# ansible-playbook SetupMailserver.yml
# https://docker-mailserver.github.io/docker-mailserver/latest/

---
- name: Setup Mailserver
  hosts: all
  tasks:

  - name: Create directory for data
    file:
      path: "{{ item }}"
      state: directory
      owner: ajorians
      group: users
      mode: 0777
    loop:
      - /opt/DockerSwarmData/mailserver
      - /opt/DockerSwarmData/mailserver/maildata
      - /opt/DockerSwarmData/mailserver/mailstate
      - /opt/DockerSwarmData/mailserver/maillogs
      - /opt/DockerSwarmData/mailserver/mailconfig
      - /root/docker
      - /root/docker/mailserver

  - name: Copy the docker-compose file with owner and permissions
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: /root/docker/mailserver
      owner: ajorians
      group: users
      mode: 0777

  - name: Deploy Mailserver from a compose file
    docker_compose:
      project_src: /root/docker/mailserver

