version: '3.9'
services:
    ersatztv:
        image: jasongdove/ersatztv
        restart: unless-stopped
        volumes:
            - '/opt/DockerSwarmData/ersatztv/tv:/tv:ro'
            - '/opt/DockerSwarmData/ersatztv/movies:/movies:ro'
            - '/opt/DockerSwarmData/ersatztv/config:/root/.local/share/ersatztv'
        ports:
            - '8409:8409' # <Host Port>:<Container Port>
        environment:
            - TZ=America/Washington
        container_name: ersatztv
