version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    # <Host Port>:<Container Port>
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/DockerSwarmData/nginxproxymanager/data:/data
      - /opt/DockerSwarmData/nginxproxymanager/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
